{
  "language": "fortran",
  "sudo": "required",
  "dist": "trusty",
  "before_install": [
    "sudo apt-get update",
    "sudo apt-get -y install build-essential debhelper",
    "chmod 755 .travis/install-icc.sh",
    "sudo .travis/install-icc.sh --components ipp,ifort --dest /opt/intel"
  ],
  "script": [
    "source /opt/intel/bin/compilervars.sh intel64",
    "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/ism/bin/intel64",
    "git clone --depth=50 --branch=master https://github.com/AquaticEcoDynamics/libaed2.git ../libaed2",
    "export AED2=true",
    "export EXTERNAL_LIBS=shared",
    "export SINGLE=false",
    "export PRECISION=1",
    "export FORTRAN_COMPILER=IFORT",
    "export CURDIR=`pwd`",
    "export AED2DIR=${CURDIR}/../libaed2",
    "export FV_CONFIGURED=true",
    "./build_tfv_aed.sh"
  ],
  "after_success": [
     "ls -l lib",
     "echo 'build status = '$TRAVIS_TEST_RESULT"
  ],
  "after_failure": [
     "echo 'fail status = '$TRAVIS_TEST_RESULT"
  ],
  "group": "stable",
  "os": "linux"
}
